# Generated by Django 6.0 on 2026-04-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="category",
            field=models.CharField(
                choices=[
                    ("Heritage", "Heritage"),
                    ("Cruiser", "Cruiser"),
                    ("Adventure", "Adventure"),
                    ("Roadster", "Roadster"),
                    ("Pure Sport", "Pure Sport"),
                ],
                default="Heritage",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="bike",
            name="engine_capacity",
            field=models.IntegerField(default=350),
        ),
    ]
